version: "3.8"
services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
  # backend:
  #   build: ./server
  #   ports:
  #     - "8088:8080"

  frontend:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    stdin_open: true
    tty: true
volumes:
  data:
